const SEPARATOR_COMMA = ','
const SEPARATOR_SPACED_FALLOW = ' -> '
const SEPARATOR_SPACED_SLASH = ' / '
const SYMBOL_EMPTY = 'e'
const SYMBOL_END = '#'

export {
    SEPARATOR_SPACED_FALLOW,
    SEPARATOR_SPACED_SLASH,
    SYMBOL_EMPTY,
    SYMBOL_END,
    SEPARATOR_COMMA,
}